apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.srv.name }}
data:
  clusterDomain: {{ .Values.clusterDomain }}
  gateway: {{ .Values.gateway }}
<% if(routes){ -%>
  namespace: {{ .Release.Namespace }}
  apiRuleGroup: {{ .Values.apiRuleGroup }}
  apiRuleVersion: {{ .Values.apiRuleVersion }}
  apiRules: {{ .Values.apiRules }}
  appServiceName: {{ .Values.services.app.name }}
  appServicePort: '{{ .Values.services.app.service.port }}'
<% } -%>
<% if(hana){ -%>
  db_api_url: https://{{ .Values.services.db.name }}.{{ .Values.clusterDomain }}
  db_api_user: {{ .Values.services.db.service.user }}
  db_api_password: {{ .Values.services.db.service.password }}
<% } -%>