apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.services.db.secretName }}
data:
  {{- $secretObject := (lookup "v1" "Secret" .Release.Namespace .Values.services.db.name) | default dict }}
  {{- $secretData := (get $secretObject "data") | default dict }}
  {{- $hdiDynamicDeployUser := (get $secretData "hdi_dynamic_deploy_user") | default (randAlphaNum 50 | b64enc) }}
  hdi_dynamic_deploy_user: {{ $hdiDynamicDeployUser | quote }}
  {{- $hdiDynamicDeployPassword := (get $secretData "hdi_dynamic_deploy_password") | default (randAlphaNum 50 | b64enc) }}
  hdi_dynamic_deploy_password: {{ $hdiDynamicDeployPassword | quote }}