apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.services.sqlite.name }}
data:
  clusterDomain: {{ .Values.clusterDomain }}
  gateway: {{ .Values.gateway }}
<% if(routes){ -%>
  namespace: {{ .Release.Namespace }}
  apiRuleGroup: {{ .Values.apiRuleGroup }}
  apiRuleVersion: {{ .Values.apiRuleVersion }}
  apiRules: {{ .Values.apiRules }}
  appServiceName: {{ .Values.services.app.name }}
  appServicePort: '{{ .Values.services.app.service.port }}'
<% } -%>
<% if(hana){ -%>
  hdi_dynamic_deploy_url: https://{{ .Values.services.db.name }}.{{ .Values.clusterDomain }}
<% } -%>