apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.sqlite.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ .Values.services.sqlite.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.sqlite.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.sqlite.name }}
    spec:
      containers:
        - image: "{{ .Values.dockerID }}/{{ .Values.services.sqlite.image.repository }}:{{ .Values.services.sqlite.image.tag }}"
          name: {{ .Values.services.sqlite.name }}
          imagePullPolicy: {{ .Values.services.sqlite.image.pullPolicy }}
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - name: http
              containerPort: {{ .Values.services.sqlite.image.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.services.sqlite.name }}
<% if(hana){ -%>
            - secretRef:
                name: {{ .Values.services.db.secretName }}
<% } -%>
          env:
            - name: SERVICE_BINDING_ROOT
              value: /bindings
          volumeMounts:
            - name: <%= projectName %>-uaa
              mountPath: "/bindings/<%= projectName %>-uaa"
              readOnly: true
            - name: <%= projectName %>-registry
              mountPath: "/bindings/<%= projectName %>-registry"
              readOnly: true
<% if(hana){ -%>
            - name: <%= projectName %>-sm
              mountPath: "/bindings/<%= projectName %>-sm"
              readOnly: true
<% } -%>
<% if(apiDest){ -%>
            - name: <%= projectName %>-dest
              mountPath: "/bindings/<%= projectName %>-dest"
              readOnly: true
<% } -%>
<% if(dockerRepositoryVisibility === 'private'){ -%>
      imagePullSecrets:
        - name: {{ .Values.services.sqlite.image.imagePullSecretName }}
<% } -%>
      volumes:
        - name: <%= projectName %>-uaa
          secret:
            secretName: {{ .Values.services.uaa.bindingSecretName }}
        - name: <%= projectName %>-registry
          secret:
            secretName: {{ .Values.services.registry.bindingSecretName }}
<% if(hana){ -%>
        - name: <%= projectName %>-sm
          secret:
            secretName: {{ .Values.services.sm.bindingSecretName }}
<% } -%>
<% if(apiDest){ -%>
        - name: <%= projectName %>-dest
          secret:
            secretName: {{ .Values.services.dest.bindingSecretName }}
<% } -%>