kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: <%= projectName %>-service-data
  labels:
    app: <%= projectName %>-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Mi