dockerID: <%= dockerID %>
clusterDomain: <%= clusterDomain %>
gateway: <%= gateway %>
services:
  db:
    name: <%= projectName %>-db
    secretName: <%= projectName %>-db-secret
    image:
<% if(dockerRepositoryName !== ''){ -%>
      repository: <%= dockerRepositoryName %>
      tag: "<%= projectName %>-db"
<% } else { -%>
      repository: <%= projectName %>-db
      tag: "latest"
<% } -%>
      pullPolicy: Always
<% if(dockerRepositoryVisibility === 'private'){ -%>
      imagePullSecretName: <%= dockerRegistrySecretName %>
<% } -%>
      port: 5002
    service:
      port: 5002